spring.datasource.url=jdbc:postgresql://localhost:5432/manzil
spring.datasource.username=postgres
spring.profiles.active=local
spring.datasource.driver-class-name=org.postgresql.Driver

# spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.ddl-auto=create

# Tells Spring to execute scripts from "resources"
spring.sql.init.mode=always

spring.sql.init.schema-locations=classpath:triggers.sql
# Use a different separator for PostgreSQL functions
spring.sql.init.separator=//