# Flexible Database Connection
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/manzil}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password}

spring.datasource.driver-class-name=org.postgresql.Driver

# IMPORTANT: Change 'always' to 'embedded' or 'never' for production
# If this is 'always', it will try to recreate triggers every time the app restarts
spring.sql.init.mode=never

spring.jpa.hibernate.ddl-auto=update
spring.sql.init.schema-locations=classpath:triggers.sql
spring.sql.init.separator=//
