spring.application.name=manzil

# Local Profiles Activation
spring.profiles.active=local

# Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/manzil
spring.datasource.username=postgres
spring.datasource.password=u211209@

# JPA / Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
